### ISSUE TITLE
[FEATURE]Regarding wait time

### ISSUE THREAD

**Issue by Caerus256** [legendsayantan/MsRewards#11]
**Is your feature request related to a problem? **
Hey sayantan, as I mentioned in last request, I understood how searches work and I would like to know if it is possible to add a option to do searches continuously without wait time, since I am having issues with search count recently I set it to 5 min each, so is there any way to get an option where searches happen without wait time(15 minutes). I know it would be causing problems to other users and am not sure if Android consider app to be battery draining. If it is possible and there is no issue, could you add an option in override presets

**Comment by legendsayantan** [comment]
The "cooldown mode" toggle in Turbo Search does exactly that. If it's not enabled, it will not wait 15 minutes .

**Comment by Caerus256** [comment]
Oh sorry forgot about that. Thanks!!
