### ISSUE TITLE
[BUG] Cant login 

### ISSUE THREAD

**Issue by hodenbreaker** [legendsayantan/MsRewards#12]
I cant login into my Account. I am not able to downgrade the system webview. It stucks on version 120. ShizuTools are also unable to downgrade to version 111. Any idea to solve the login Problem. My phone is a Pixel 7 with android 14.
![Screenshot_20240316-142123](https://github.com/legendsayantan/MsRewards/assets/156360043/0c1cf5de-6d13-447c-b18b-d46c79510fe0)

**Comment by SsimplyDan** [comment]
Same here App ID - -1120860220-58898e31-f9ab-40a5-8b01-e56265e137f2

**Comment by legendsayantan** [comment]
If on-device login doesn't work at all, you can login by extracting accounts from other browser. It's a bit complicated, but can work as a temporary solution.

https://github.com/legendsayantan/Rewards-Login

As for ShizuTools not being able to downgrade, what steps did you take and what was the exact result?

**Comment by hodenbreaker** [comment]
I installed shizuku, paired everything and gave permissions to ShizuTools.
Unfortunately, Android Web View is not displayed for me on lookback.  I
could only delete it completely with debloat



Sayantan Paul ***@***.***> schrieb am Mo., 18. März 2024,
05:22:

**Comment by hodenbreaker** [comment]
I can add my account via clipboard, but as soon as I reload the account,
the app says that the account has been logged out by Microsoft.
Unfortunately I can't start a search with this.

Stefan ***@***.***> schrieb am Mo., 18. März 2024, 20:07:

**Comment by SsimplyDan** [comment]
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0cm;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:612.0pt 792.0pt;
	margin:72.0pt 72.0pt 72.0pt 72.0pt;}
div.WordSection1
	{page:WordSection1;}

**Comment by legendsayantan** [comment]
@hodenbreaker LookBack is not supposed to "display" apps. Once you have an app with newer version installed, find an apk online with an older version that is compatible with your device, and select the apk file when LookBack asks you to. it only helps you overwrite an existing app installation.

**Comment by hodenbreaker** [comment]
I tried the downgrade again, but unfortunately without success. I have many arm64-v8a versions, all without success. I always get the error message that the package is invalid
![Screenshot_20240319-163611](https://github.com/legendsayantan/MsRewards/assets/156360043/bdccbd6e-d970-4353-b2d7-4b77c3f10e5c)

**Comment by SsimplyDan** [comment]
![Screenshot 2024-03-19 184551](https://github.com/legendsayantan/MsRewards/assets/104859691/ccd2c711-8991-4d80-b94f-042e89547211)
I am logged in but nothing happens

**Comment by SsimplyDan** [comment]
![Screenshot_2024 03 19_18 52 17 350](https://github.com/legendsayantan/MsRewards/assets/104859691/f255f1e5-e009-4f14-99aa-1e483efe884c)
I am also not getting points for opening the app. 
App ID - -1120860220-0f245c1d-cc6b-4afa-a51d-566b4573a4f3

**Comment by SsimplyDan** [comment]
New App ID -1120860220-e8f744e1-966e-49c7-b2a1-0627644949cc

**Comment by legendsayantan** [comment]
@SsimplyDan  

For the login issue, could you Uninstall updates to Android System Webview? 

For the points, if you have already installed the app previously then you need to wait one day after installation to get the points.

**Comment by legendsayantan** [comment]
@hodenbreaker has this problem started recently for you? If so, since how long?

**Comment by hodenbreaker** [comment]
I always had this error when I logged out of the Microsoft account. Then I installed rewards version 1.1.7, logged in and updated to 1.2.2. Unfortunately that doesn't work anymore. @SsimplyDan were you able to downgrade?

**Comment by SsimplyDan** [comment]
![image](https://github.com/legendsayantan/MsRewards/assets/104859691/1964b36e-d3e8-4a57-ab3d-7b135bc40528)

![Screenshot_2024 03 21_22 21 58 217](https://github.com/legendsayantan/MsRewards/assets/104859691/d7758ebd-d1b4-4d12-92b4-f044ea5d6a5f)
![Screenshot_2024 03 21_22 23 39 250](https://github.com/legendsayantan/MsRewards/assets/104859691/8977cef3-7087-4fd3-a411-ae974dc2940e)

This whole problem started when I uninstalled rewards with my account in it because my automation quota was around -2000 (minus 2000) because it kept doing extra activities but did not complete them. Then I reinstalled to sign back in but when I sign in, I am just stuck on the web until I press cancel. I don't know if the app thinks I've already used the account because I deleted it and reinstalled.

**Comment by SsimplyDan** [comment]
![Screenshot_2024 03 21_22 28 02 784](https://github.com/legendsayantan/MsRewards/assets/104859691/b058ff15-fa6f-45c2-afc8-2f764111aec4)
ShizuTools also does not work it just keeps staying on this screen.

**Comment by SsimplyDan** [comment]
I am also using bluestacks on laptop because I don't have an android device.

**Comment by legendsayantan** [comment]
@SsimplyDan  app wasn't designed for emulators, and I'd advise you not to use it on there. Android in itself is a complicated environment for these apps to run, and emulator platforms make them more complicated and harder to debug.

**Comment by legendsayantan** [comment]
@hodenbreaker do you have access to a computer?

**Comment by hodenbreaker** [comment]
@legendsayantan yes

**Comment by legendsayantan** [comment]
@hodenbreaker You can install the chrome extension by following [these instructions](https://github.com/legendsayantan/Rewards-Login?tab=readme-ov-file#how-to-use--), and export account data from chrome to use in the Rewards app.

**Comment by hodenbreaker** [comment]
I've already done that. Then the login works. However, I don't have any points to carry out the search and after 24 hours the app says that the account has been logged out of Microsoft. When I log in again, it happens the same way.

**Comment by SsimplyDan** [comment]
@legendsayantan 
![be33645c-3375-4fd0-9c05-fa676ac861f3](https://github.com/legendsayantan/MsRewards/assets/104859691/ed3504c7-7120-4b43-b997-bc5e75345784)
![372eda1e-64c4-4b41-b300-84fc18f553ce](https://github.com/legendsayantan/MsRewards/assets/104859691/58826ef7-4801-4db8-bc9c-93248aa062d9)
There is no sign in button it's too zoomed in. This is on an android device - Samsung.
ShizuTools still not working

**Comment by SsimplyDan** [comment]
All fixed now just had to redownload my android emulator - bluestacks.

**Comment by SsimplyDan** [comment]
What does Auto-Queue do?

**Comment by legendsayantan** [comment]
The sign in button not showing could be an internet issue, and the Shizutools app won't start until you have installed and started **Shizuku** ([this app](https://shizuku.rikka.app)) as well.

Auto queue starts remaining tasks of an account one after another, but it uses the legacy way, not compatible with turbo search. So it's pretty useless nowadays.

**Comment by SsimplyDan** [comment]
@legendsayantan Ok thank you.

**Comment by legendsayantan** [comment]
@hodenbreaker on Rewards v1.2.3, you can 
1. First, uninstall the Android system WebView to the lowest possible version normally, then 
2. Enable "Enforce WebView" in custom config to make the app *attempt* to work with your installed version of the WebView. 
I cannot guarantee this will always work, but this is a viable last resort.

**Comment by vjaykrsna** [comment]
> ![Screenshot 2024-03-19 184551](https://private-user-images.githubusercontent.com/104859691/314191439-ccd2c711-8991-4d80-b94f-042e89547211.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU0ODM2OTIsIm5iZiI6MTczNTQ4MzM5MiwicGF0aCI6Ii8xMDQ4NTk2OTEvMzE0MTkxNDM5LWNjZDJjNzExLTg5OTEtNGQ4MC1iOTRmLTA0MmU4OTU0NzIxMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyOVQxNDQzMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jY2JjNmVkNGIyYTgzZTNhYzFkOWEyYTc1NzhmMzFmNzU1MjIzYTczY2E5MjY3MjgyMDNjZTAzZWJjMWMxNGMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.abcK5iYrXghhm6jUWVAv7hRzQIhGW6YLiVIzt101NHw) I am logged in but nothing happens

were you able to solve this?
how did you login then
i am also stuck after login and don't know what to do

**Comment by SsimplyDan** [comment]
I had to redownload bluestacks for it to work.
