### ISSUE TITLE
[BUG] MObile searches arent being counted

### ISSUE THREAD

**Issue by Khaos1221** [legendsayantan/MsRewards#13]
**Describe the bug**
It is occuring every day , but Pc search continues to work
**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [Poco C3 root]
 - OS: [ Android 12]

**Additional context**
If I search with a browser then yes it will log points , I have checked

**Comment by legendsayantan** [comment]
Can you provide some more information? Like if you're using turbo search or not, if you have cooldown mode enabled or not, and do you have Override Presets enabled?

**Comment by Khaos1221** [comment]
I use normal mode (no VIP) ,, the searches take up automation points but still 20 searches remain and no points are added. 
SOme times in Turbo mode , MObile searches are counted and give me reward points

**Comment by legendsayantan** [comment]
I'm not sure what you mean by "VIP", and when you do get rewards points in turbo are you using the Efficienct or Performant engine?

**Comment by legendsayantan** [comment]
Closed for inactivity.

**Comment by Khaos1221** [comment]
> I'm not sure what you mean by "VIP", and when you do get rewards points in turbo are you using the Efficienct or Performant engine?

Efficient
