### ISSUE TITLE
Automation Quota in the minus

### ISSUE THREAD

**Issue by SsimplyDan** [legendsayantan/MsRewards#14]
![Screenshot_2024 04 04_13 43 02 125](https://github.com/legendsayantan/MsRewards/assets/104859691/1e30b7b4-c17b-4d50-bc78-877e7480b70b)
My automation quota went into the minus when I clicked on completing extra activities. I think this happens because it keeps doing it even when they are all completed, resulting in the numbers going into the minus.

Please give me 450 quotas back to resolve this because it was not my fault.
App ID - -595043281-d0e52e81-0732-4f7a-8ea7-cd4e2f132cca

**Comment by legendsayantan** [comment]
1. You were already informed that running this app on emulator is discouraged.
2. According to the [Usage Agreement](https://github.com/legendsayantan/MsRewards/blob/main/PRIVACY.md), there are no warranties that the app must always work.
3. The quota you lost, was already given to you for free by the app.
4. It's not currently possible to provide custom amounts, other than the plans.
