### ISSUE TITLE
[SPONSOR] @IntheDark

### ISSUE THREAD

**Issue by legendsayantan** [legendsayantan/MsRewards#17]
@IntheDark 

**Provide your app ID below this line.**
-

**Comment by IntheDark** [comment]
Greetings, @legendsayantan

This is my app ID:
-1163883676-0f3a20f4-d68e-487c-89ae-eb25e7fbec97

**Comment by legendsayantan** [comment]
Your activation url -

https://rewards.is-an.app/?action=redeem&code=77792a966ecab2ef311e2d9901b7be751475113a42314072f712cc631a54322248eedcf4e070373c0de8977f66f1e35f5bb66f5fe67584ae0a19eed79050ad64ead361fbf4d018a5fe15602fdc3cc51e16c2353933d19fcd20d198ed151ebd459f18a6b64b42b6f651350d34bc6ef4882757915cb2ae8d5a511a0c27271c287e7831e594b713157954f36af67c4a569d228fff7e8ce09f6062d2cd34aa95fb22fa18441919737e84ba100587120f314fb36453e1dc198f99fff356565b637849c3f3f5f02003ed8a71fe51a7d810d481be14448d97802ca0bcda0d851e4b13dd4b8f3281c5aff83de196764beebd07c62543ac48d5d04c4f0ee02a98e0cebc1b&amount=6000
