### ISSUE TITLE
Can I run the application on Android virtual machines?

### ISSUE THREAD

**Issue by beenruuu** [legendsayantan/MsRewards#18]
I want to know if I can run the application on a virtual machine that emulates an Android device, I don't know if it will put the security of my account at risk because it can be detectable but I wanted to check it before, thank you!

**Comment by legendsayantan** [comment]
it is not advisable to run this app on android virtual machines or emulators, the app won't even start on some of them.

**Comment by legendsayantan** [comment]
Update: since version 1.2.6 there is support for emulators and virtual machines, but require special permissions to do so, in order to eliminate the abuse potential.
