### ISSUE TITLE
Not redirecting to login page

### ISSUE THREAD

**Issue by Caerus256** [legendsayantan/MsRewards#2]
Hey! i hvae used v1.1.6 and never faced an issue but in v 1.1.7 when i am tring to add a account instead of going to account login page it stays in bing search page, and even when i force it to add the account by going to login page using sidebar, the app doesn't move forward. I hope you fix it

Thanks

**Comment by andvip0** [comment]
+

**Comment by legendsayantan** [comment]
Can you attach a screenshot of what your issue looks like?

**Comment by Caerus256** [comment]
> Can you attach a screenshot of what your issue looks like?

https://ibb.co/c836xnv

After clicking on add account, it goes to bing but doesn't redirect to login page, i have tried adding account by going to rewards page using sidebar in bing search but app doesn't move forward. I have tried reinstalling and deleted old data but none seems to be working.

**Comment by legendsayantan** [comment]
Understood. I recently saw others having this issue too.
Unfortunately, the code responsible hasn't been changed since app version 1.1.6, so this issue must be introduced by something Microsoft did. Will look into a possible fix.
