### ISSUE TITLE
Permission to use on Bluestacks emulator

### ISSUE THREAD

**Issue by SsimplyDan** [legendsayantan/MsRewards#25]
I need special permission to use it on Bluestacks since I had to reinstall it. I also lost over 4k points, there should be a way to keep all the points.

**Comment by legendsayantan** [comment]
When you purchase, there is a popup notice that says you will lose points
if you reinstall without ticking the "keep app data" box.
Also, for the special permission on the emulator, share the emulator ID you
can find on the app.

**Comment by SsimplyDan** [comment]
It shows a white screen when I open the app.

**Comment by legendsayantan** [comment]
Open the "app info" page for Rewards, go to storage/space, then click on
clear data/clear storage. From there the emulator ID should be easily
visible.

**Comment by SsimplyDan** [comment]
![Screenshot 2024-10-29 011444](https://github.com/user-attachments/assets/d2e91494-f91d-4dc4-8fa7-9a5e5a1e4714)

**Comment by legendsayantan** [comment]
You were authorised. Clear all the app data after 12-24 hours and it should start working after that.

**Comment by SsimplyDan** [comment]
How do I do that?
