### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by SsimplyDan** [legendsayantan/MsRewards#27]
I got signed out from my accounts but when I tried to log back in, it left me on this screen. I have also enforced webview.
My device ID: bf853eb9df6627ee
I've noticed that the only way to fix it is to reinstall Bluestacks and the rewards app. But in the process, I lost all the points I bought with money. Which is about 4.8k points

![Screenshot_2024 11 16_01 18 27 314](https://github.com/user-attachments/assets/951c7a81-8ef8-4f4b-be6c-6afa3600f2bd)

**Comment by legendsayantan** [comment]
The correct approach is not to enforce webview until you need it. Even when you do need it, always click the "quick fix" button first, check if it works after that and then enforce webview if it still doesn't. 

for the lost points, share your full App ID so I can reimburse them (this time only)

**Comment by SsimplyDan** [comment]
Alright I need verification. Device ID: 22fe535da5d9454e

**Comment by legendsayantan** [comment]
Permitted.

**Comment by SsimplyDan** [comment]
> The correct approach is not to enforce webview until you need it. Even when you do need it, always click the "quick fix" button first, check if it works after that and then enforce webview if it still doesn't.
> 
> for the lost points, share your full App ID so I can reimburse them (this time only)

App ID: 1888169255-738abbe8-e5d9-4cb7-94b3-2a0af41b0bf5

**Comment by legendsayantan** [comment]
https://rewards.is-an.app/?action=redeem&code=6a79c45eb40217df2b6b02c0362cadc6c91206e49e17e92b8b3aedab8613cc317b14ab6707b7b482b1c08c46c3ee2dd9ae28bc7684246832c960bdc7d3e5e22c95a02843c32027851b2c2f588a4f3ddc97d953913854310ac24bf9f35a059b2d6c331f9f79d29d3f60b624054d6816d66f13101312cd192d4861204ea380daa46e225ad5b344564096167685b639ae3611495d0268cb9e10a0e9f3eb4e2206dbc29982d10bf03883cf5bfa430dee01c36627fd27abd0ff83451e5894c5921f39ba1acf9ab43cfc49a171418ee582169a005e3ae9a1e484fe017cbad558577251cce0e8dc0af158060ac582a57358c4037b430e4e39d083a9ac017c6e678b10f2&amount=6000
