### ISSUE TITLE
Sponsorship by @servilta2

### ISSUE THREAD

**Issue by legendsayantan** [legendsayantan/MsRewards#6]
Hi @servilta2, you have sponsored this project but I can't find a way to contact you , so I can give you the benefits of it. Please share your App ID here to get the license, or alternatively provide any contact details.

**Comment by SERVILTA2** [comment]
Hello, ok this is my app ID: 4aebc059-8a41-47f0-bc45-2e1610822a84

**Comment by SERVILTA2** [comment]
Here you have it

**Comment by SERVILTA2** [comment]
My Gmail address is Joelalcasen@gmail.com

**Comment by legendsayantan** [comment]
I have mailed you your quota claim url.

**Comment by SERVILTA2** [comment]
I havent received anything on my Gmail

**Comment by SERVILTA2** [comment]
![Screenshot_20240129_173958_Gmail](https://github.com/legendsayantan/MsRewards/assets/157470560/b15690e3-a27a-44d1-b50f-006f4c37ee53)
![Screenshot_20240129_174001_Gmail](https://github.com/legendsayantan/MsRewards/assets/157470560/a63eade0-61e1-4d4c-b65b-a3c7e54f2563)



Send it to my secondary Gmail account, joelqlcaide@gmail.com

**Comment by SERVILTA2** [comment]
helloo?

**Comment by legendsayantan** [comment]
I'm dropping the url here.
https://rewards.is-an.app/?action=redeem&code=336e26e4dedd98a33dae01b618fc55b1cf8e0330705f0d656201155ef9d37c6f89316507fc9d93f89e3d04bf9906f16b23aa3a625fca006456606211fda991d0d7e7510565ec32c83366e391d35dfeff9c41bc698ceafbcfda106407e0156cc83687f91a2f10de35cd8fe72afba61d16d776ed1553525204e6a6afd71dbae995311644e2af2dea07ba89e1cbe2f88d94b76f227227bfb68523e32b1c2bc25e3cb71b9b09b2f2355bcb30156e5211d7966fedbc1b9a2c139c3970f06722050048215a55bff64c0673ac84cdbeaaa31d32ed024a5c2a8fa69647713e0a155fb1c309db02d253e5b8c857fc57f2e29ac25c72ca5eb79ba1391806e1a0ff51867545&amount=20000
