### ISSUE TITLE
[BUG]issue regarding the Android system Webview

### ISSUE THREAD

**Issue by Caerus256** [legendsayantan/MsRewards#7]
**Describe the bug**
Whenever i try to add an account or run the point tasks, it asks me to uninstall Android system Webview even after uninstalling it, previously it used to work fine after uninstalling the System Webview app(version 121.0.6167.164) which my device comes prebuilt with.

**Smartphone (please complete the following information):**
 -  Vivo IQOO 9
 - OS: Android 14

**Comment by legendsayantan** [comment]
Unfortunately, v121 of Android system webview isn't compatible. 
Possible workarounds -
1. Downgrade **Android System Webview** further than the prebuilt version , can be achieved via adb or ShizuTools.
2. Use the Rewards-Login browser extension to add accounts in the app using a desktop browser, then run Turbo Search in Efficient mode (Efficient mode doesn't depend on Android System Webview)

**Comment by Caerus256** [comment]
Could you please add support to v121 too since previous to this update in every version I was able to use turbo search and every features. I am facing the issue only in new version, since v1.2.0

**Comment by Caerus256** [comment]
> Unfortunately, v121 of Android system webview isn't compatible. Possible workarounds -
> 
> 1. Downgrade **Android System Webview** further than the prebuilt version , can be achieved via adb or ShizuTools.
> 2. Use the Rewards-Login browser extension to add accounts in the app using a desktop browser, then run Turbo Search in Efficient mode (Efficient mode doesn't depend on Android System Webview)

I have searched for the methods mentioned.
1. It requires root and can't be done using shizuku or adb. If you could reference me to any method, please send me.
2. I am not sure what it meant, could you explain them more.
Thanks

**Comment by Caerus256** [comment]
Have successfully downgraded to v120.0.6099.232 webview version using shizutools but was still getting the error. 

![Screenshot_20240217_093222](https://github.com/legendsayantan/MsRewards/assets/60589553/039d5586-cb0f-444d-b7ce-e3f6e4606d9d)

**Comment by legendsayantan** [comment]
If it's possible to downgrade to v111 or below , it should not give any errors.

In newer versions of Android system webview, it dropped the ability to emulate desktop browsers properly. The regular PC search, Performant Turbo Search and the login algorithm will not work with v121, as they require to communicate with bing in Desktop Mode.

I have experimented with embedding an independent browser engine, and found that will inflate app size from 3 mb to 60-70 mb and will still require an entire re-work of the algorithms working under the hood.
