### ISSUE TITLE
Sponsorship by @hodenbreaker

### ISSUE THREAD

**Issue by legendsayantan** [legendsayantan/MsRewards#9]
Hello, and thanks for supporting the development of my software. If you would like to avail the benefits in [Rewards](https://github.com/legendsayantan/MsRewards) app, please copy your App ID and paste it below.

@hodenbreaker

**Comment by hodenbreaker** [comment]
Here is my App ID:
ba8224d0-fb3b-4e8e-aec0-2ad627f3488b
Thank you!

**Comment by legendsayantan** [comment]
Here's your activation link -
https://rewards.is-an.app/?action=redeem&code=9af90cbc593ab2283110faa1954c171682c6fab0bc0e5ecd32adf65f7d3705d1395a2adede5950c5f0527f7733512e147192896d4343327369361c9a14567dfd9a22a83dbf9f23dcc771f0317d8ba1de0227dec7f107fe1ed3bc5936326a2e567faf34ce16125443480628a224a9eebe292cc20c0e6ef7d7955fcf551d9c94d62f0bfedd4f205fd080043f7c55038e9d89bf1cee010c9ef1630e1fa47400088f716af06e52237734128ddfc0bb1719f4331b2625dc91625e6e5ae5b8f321ff9ed62babfc0010be7be02c1b456929640a560a7806ec29840bd2972db5981c8fc3427984cdfb3280c95947597fac359d78d684962b8dd78f7efc05220601289491&amount=20000
